package gui.dialogs;

import classes.Jogador;
import gerentes.GerenteElenco;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Davi
 */
public class CentralTransferencia extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CentralTransferencia.class.getName());
    
    private final ArrayList<Jogador> listaJogadores = new ArrayList<>();
    private final GerenteElenco gerenteElenco;

    public CentralTransferencia(java.awt.Frame parent, boolean modal, gerentes.GerenteElenco gerenteElenco) {
        super(parent, modal);
        System.out.println("CRIADA CENTRAL: " + this);

        
        this.gerenteElenco = gerenteElenco;
        
        initComponents();
        
        pnlBotoesPrincipais.setBackground(new java.awt.Color(30, 30, 30));
        getContentPane().setBackground(new java.awt.Color(30,30,30));

        botoesEscondidos();
        designBotoes(btnListaAlvos);
        designBotoesJogador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotoesPrincipais = new javax.swing.JPanel();
        btnListaAlvos = new javax.swing.JButton();
        btnPropostasEnviadas = new javax.swing.JButton();
        btnPropostasRecebidas = new javax.swing.JButton();
        btnAgentesLivres = new javax.swing.JButton();
        Parent = new javax.swing.JPanel();
        ListaAlvos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnJogador1 = new javax.swing.JButton();
        btnJogador2 = new javax.swing.JButton();
        btnJogador3 = new javax.swing.JButton();
        btnJogador4 = new javax.swing.JButton();
        btnJogador5 = new javax.swing.JButton();
        btnJogador6 = new javax.swing.JButton();
        PropostasEnviadas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(30, 30, 30));
        setResizable(false);

        pnlBotoesPrincipais.setBackground(new java.awt.Color(30, 30, 30));
        pnlBotoesPrincipais.setForeground(new java.awt.Color(30, 30, 30));

        btnListaAlvos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnListaAlvos.setForeground(new java.awt.Color(255, 255, 255));
        btnListaAlvos.setText("LISTA DE ALVOS");
        btnListaAlvos.addActionListener(this::btnListaAlvosActionPerformed);

        btnPropostasEnviadas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPropostasEnviadas.setForeground(new java.awt.Color(255, 255, 255));
        btnPropostasEnviadas.setText("PROPOSTAS ENVIADAS");

        btnPropostasRecebidas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPropostasRecebidas.setForeground(new java.awt.Color(255, 255, 255));
        btnPropostasRecebidas.setText("PROPOSTAS RECEBIDAS");

        btnAgentesLivres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgentesLivres.setForeground(new java.awt.Color(255, 255, 255));
        btnAgentesLivres.setText("AGENTES LIVRES");
        btnAgentesLivres.addActionListener(this::btnAgentesLivresActionPerformed);

        javax.swing.GroupLayout pnlBotoesPrincipaisLayout = new javax.swing.GroupLayout(pnlBotoesPrincipais);
        pnlBotoesPrincipais.setLayout(pnlBotoesPrincipaisLayout);
        pnlBotoesPrincipaisLayout.setHorizontalGroup(
            pnlBotoesPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesPrincipaisLayout.createSequentialGroup()
                .addComponent(btnListaAlvos, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPropostasEnviadas, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPropostasRecebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAgentesLivres, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
        );
        pnlBotoesPrincipaisLayout.setVerticalGroup(
            pnlBotoesPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotoesPrincipaisLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlBotoesPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPropostasRecebidas, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnPropostasEnviadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListaAlvos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgentesLivres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Parent.setBackground(new java.awt.Color(50, 50, 50));
        Parent.setPreferredSize(new java.awt.Dimension(0, 620));
        Parent.setLayout(new java.awt.CardLayout());

        ListaAlvos.setBackground(new java.awt.Color(30, 30, 30));
        ListaAlvos.setMaximumSize(new java.awt.Dimension(30, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Atletas Monitorados");

        btnJogador1.setBackground(new java.awt.Color(51, 51, 51));
        btnJogador1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJogador1.setForeground(new java.awt.Color(255, 255, 255));
        btnJogador1.setText("jButton1");
        btnJogador1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnJogador1.addActionListener(this::btnJogador1ActionPerformed);

        btnJogador2.setBackground(new java.awt.Color(51, 51, 51));
        btnJogador2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJogador2.setForeground(new java.awt.Color(255, 255, 255));
        btnJogador2.setText("jButton1");
        btnJogador2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnJogador3.setBackground(new java.awt.Color(51, 51, 51));
        btnJogador3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJogador3.setForeground(new java.awt.Color(255, 255, 255));
        btnJogador3.setText("jButton1");
        btnJogador3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnJogador4.setBackground(new java.awt.Color(51, 51, 51));
        btnJogador4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJogador4.setForeground(new java.awt.Color(255, 255, 255));
        btnJogador4.setText("jButton1");
        btnJogador4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnJogador5.setBackground(new java.awt.Color(51, 51, 51));
        btnJogador5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJogador5.setForeground(new java.awt.Color(255, 255, 255));
        btnJogador5.setText("jButton1");
        btnJogador5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnJogador6.setBackground(new java.awt.Color(51, 51, 51));
        btnJogador6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJogador6.setForeground(new java.awt.Color(255, 255, 255));
        btnJogador6.setText("jButton1");
        btnJogador6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnJogador6.addActionListener(this::btnJogador6ActionPerformed);

        javax.swing.GroupLayout ListaAlvosLayout = new javax.swing.GroupLayout(ListaAlvos);
        ListaAlvos.setLayout(ListaAlvosLayout);
        ListaAlvosLayout.setHorizontalGroup(
            ListaAlvosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaAlvosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaAlvosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListaAlvosLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 828, Short.MAX_VALUE))
                    .addComponent(btnJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJogador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJogador3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJogador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJogador5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJogador6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ListaAlvosLayout.setVerticalGroup(
            ListaAlvosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaAlvosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJogador3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJogador4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJogador5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJogador6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        Parent.add(ListaAlvos, "card2");

        PropostasEnviadas.setBackground(new java.awt.Color(50, 50, 50));

        javax.swing.GroupLayout PropostasEnviadasLayout = new javax.swing.GroupLayout(PropostasEnviadas);
        PropostasEnviadas.setLayout(PropostasEnviadasLayout);
        PropostasEnviadasLayout.setHorizontalGroup(
            PropostasEnviadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        PropostasEnviadasLayout.setVerticalGroup(
            PropostasEnviadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );

        Parent.add(PropostasEnviadas, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBotoesPrincipais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Parent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBotoesPrincipais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogador6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogador6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJogador6ActionPerformed

    private void btnJogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJogador1ActionPerformed

    private void btnListaAlvosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaAlvosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaAlvosActionPerformed

    private void btnAgentesLivresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgentesLivresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgentesLivresActionPerformed

    public void botoesEscondidos(){
        btnJogador1.setVisible(false);
        btnJogador2.setVisible(false);
        btnJogador3.setVisible(false);
        btnJogador4.setVisible(false);
        btnJogador5.setVisible(false);
        btnJogador6.setVisible(false);
    }

    public boolean adicionarJogador(Jogador jogador){
        
        System.out.println(jogador.getNome());

        if(listaJogadores.size() >= 6){
            return false;
        }

        if(listaJogadores.contains(jogador)){
            return false;
        }
        System.out.println("ADICIONANDO EM: " + this);

        listaJogadores.add(jogador);

        setJogadoresBotoes();

        return true;
    }
    
    public void setJogadoresBotoes(){
        JButton[] botoes = {
            btnJogador1,
            btnJogador2,
            btnJogador3,
            btnJogador4,
            btnJogador5,
            btnJogador6
        };
        
        for(int i = 0; i < botoes.length; i++){
            if(i < listaJogadores.size()){
                Jogador jogador = listaJogadores.get(i);
                String nomeTime = "";
                if(gerenteElenco.jogadorTemTime(jogador.getId()) == true){
                    nomeTime = gerenteElenco.buscarTimeDoJogador(jogador.getId()).getNome();
                }
                else{
                    nomeTime = "Sem time";
                }
                
                botoes[i].setText(
                    String.format("%-30s %-50s %5s",
                        jogador.getNome(),
                        nomeTime,
                        String.format("€ %,.0f", jogador.getValorTransferencia())
                    )
                );
                
                botoes[i].setVisible(true);
            }
            else{
                botoes[i].setVisible(false);
            }
        }
        revalidate();
        repaint();
    }
    
    public void designBotoesJogador(){
        btnJogador1.setFont(new Font("Monospaced", Font.PLAIN, 18));
        btnJogador2.setFont(new Font("Monospaced", Font.PLAIN, 18));
        btnJogador3.setFont(new Font("Monospaced", Font.PLAIN, 18));
        btnJogador4.setFont(new Font("Monospaced", Font.PLAIN, 18));
        btnJogador5.setFont(new Font("Monospaced", Font.PLAIN, 18));
        btnJogador6.setFont(new Font("Monospaced", Font.PLAIN, 18));
        
        
    }
    
    
    public void definePadraoBotao(javax.swing.JButton botao){
        botao.setBorderPainted(false);
        botao.setFocusPainted(false);
    }
    
    public void defineTodosBotoesPadrao(){
        definePadraoBotao(btnListaAlvos);
        definePadraoBotao(btnPropostasEnviadas);
        definePadraoBotao(btnPropostasRecebidas);
        definePadraoBotao(btnAgentesLivres);
        
        definePadraoBotao(btnJogador1);
        definePadraoBotao(btnJogador2);
        definePadraoBotao(btnJogador3);
        definePadraoBotao(btnJogador4);
        definePadraoBotao(btnJogador5);
        definePadraoBotao(btnJogador6);
    }
    
    public void designBotoes(javax.swing.JButton botao){
        btnListaAlvos.setBackground(new Color(51,51,51));
        btnPropostasEnviadas.setBackground(new Color(51,51,51));
        btnPropostasRecebidas.setBackground(new Color(51,51,51));
        btnAgentesLivres.setBackground(new Color(51,51,51));
        
        botao.setContentAreaFilled(true);
        botao.setOpaque(true);
        botao.setBackground(new Color(204,0,204));
        
        definePadraoBotao(botao);
        defineTodosBotoesPadrao();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListaAlvos;
    private javax.swing.JPanel Parent;
    private javax.swing.JPanel PropostasEnviadas;
    private javax.swing.JButton btnAgentesLivres;
    private javax.swing.JButton btnJogador1;
    private javax.swing.JButton btnJogador2;
    private javax.swing.JButton btnJogador3;
    private javax.swing.JButton btnJogador4;
    private javax.swing.JButton btnJogador5;
    private javax.swing.JButton btnJogador6;
    private javax.swing.JButton btnListaAlvos;
    private javax.swing.JButton btnPropostasEnviadas;
    private javax.swing.JButton btnPropostasRecebidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlBotoesPrincipais;
    // End of variables declaration//GEN-END:variables
}
