package gui.dialogs;

import classes.Jogador;
import gerentes.GerenteElenco;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Davi
 */
public class CentralTransferencia extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CentralTransferencia.class.getName());
    
    private final ArrayList<Jogador> listaJogadores = new ArrayList<>();
    private final GerenteElenco gerenteElenco;

    public CentralTransferencia(java.awt.Frame parent, boolean modal, gerentes.GerenteElenco gerenteElenco) {
        super(parent, modal);
        
        this.gerenteElenco = gerenteElenco;
        
        initComponents();
        
        String nome = "Kyllian Mbappe (MEI)";
        String time = "Santos";
        String valor = "R$ 1800000";

        btnJogador1.setFont(new Font("Monospaced", Font.PLAIN, 18));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotoesPrincipais = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        Parent = new javax.swing.JPanel();
        ListaAlvos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnJogador1 = new javax.swing.JButton();
        btnJogador2 = new javax.swing.JButton();
        btnJogador3 = new javax.swing.JButton();
        btnJogador4 = new javax.swing.JButton();
        btnJogador5 = new javax.swing.JButton();
        btnJogador6 = new javax.swing.JButton();
        PropostasEnviadas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 204));
        setResizable(false);

        pnlBotoesPrincipais.setBackground(new java.awt.Color(50, 50, 50));

        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton2.setText("LISTA DE ALVOS");
        jToggleButton2.addActionListener(this::jToggleButton2ActionPerformed);

        jToggleButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton3.setText("PROPOSTAS ENVIADAS");
        jToggleButton3.addActionListener(this::jToggleButton3ActionPerformed);

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton1.setText("PROPOSTAS RECEBIDAS");
        jToggleButton1.addActionListener(this::jToggleButton1ActionPerformed);

        jToggleButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton4.setText("AGENTES LIVRES");

        javax.swing.GroupLayout pnlBotoesPrincipaisLayout = new javax.swing.GroupLayout(pnlBotoesPrincipais);
        pnlBotoesPrincipais.setLayout(pnlBotoesPrincipaisLayout);
        pnlBotoesPrincipaisLayout.setHorizontalGroup(
            pnlBotoesPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesPrincipaisLayout.createSequentialGroup()
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
        );
        pnlBotoesPrincipaisLayout.setVerticalGroup(
            pnlBotoesPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotoesPrincipaisLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlBotoesPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
        );

        Parent.setBackground(new java.awt.Color(50, 50, 50));
        Parent.setPreferredSize(new java.awt.Dimension(0, 620));
        Parent.setLayout(new java.awt.CardLayout());

        ListaAlvos.setBackground(new java.awt.Color(30, 30, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Atletas Monitorados");

        btnJogador1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJogador1.setText("jButton1");
        btnJogador1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnJogador2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJogador2.setText("jButton1");
        btnJogador2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnJogador3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJogador3.setText("jButton1");
        btnJogador3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnJogador4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJogador4.setText("jButton1");
        btnJogador4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnJogador5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJogador5.setText("jButton1");
        btnJogador5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnJogador6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJogador6.setText("jButton1");
        btnJogador6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnJogador6.addActionListener(this::btnJogador6ActionPerformed);

        javax.swing.GroupLayout ListaAlvosLayout = new javax.swing.GroupLayout(ListaAlvos);
        ListaAlvos.setLayout(ListaAlvosLayout);
        ListaAlvosLayout.setHorizontalGroup(
            ListaAlvosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaAlvosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaAlvosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListaAlvosLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 828, Short.MAX_VALUE))
                    .addComponent(btnJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJogador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJogador3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJogador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJogador5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJogador6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ListaAlvosLayout.setVerticalGroup(
            ListaAlvosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaAlvosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJogador3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJogador4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJogador5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJogador6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        Parent.add(ListaAlvos, "card2");

        PropostasEnviadas.setBackground(new java.awt.Color(50, 50, 50));

        javax.swing.GroupLayout PropostasEnviadasLayout = new javax.swing.GroupLayout(PropostasEnviadas);
        PropostasEnviadas.setLayout(PropostasEnviadasLayout);
        PropostasEnviadasLayout.setHorizontalGroup(
            PropostasEnviadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        PropostasEnviadasLayout.setVerticalGroup(
            PropostasEnviadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );

        Parent.add(PropostasEnviadas, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBotoesPrincipais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Parent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBotoesPrincipais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnJogador6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogador6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJogador6ActionPerformed


    public boolean adicionarJogador(Jogador jogador){

        if(listaJogadores.size() >= 6){
            return false;
        }

        if(listaJogadores.contains(jogador)){
            return false;
        }

        listaJogadores.add(jogador);

        setJogadoresBotoes();

        return true;
    }
    
    public void setJogadoresBotoes(){
        JButton[] botoes = {
            btnJogador1,
            btnJogador2,
            btnJogador3,
            btnJogador4,
            btnJogador5,
            btnJogador6
        };
        
        for(int i = 0; i < botoes.length; i++){
            if(i < listaJogadores.size()){
                Jogador jogador = listaJogadores.get(i);
                
                btnJogador1.setText(
                    String.format("%-30s %-50s %10s",
                        jogador.getNome(),
                        gerenteElenco.buscarTimeDoJogador(jogador.getId()),
                        jogador.getValorTransferencia()
                    )
                );
                
                botoes[i].setVisible(true);
            }
            else{
                botoes[i].setVisible(false);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListaAlvos;
    private javax.swing.JPanel Parent;
    private javax.swing.JPanel PropostasEnviadas;
    private javax.swing.JButton btnJogador1;
    private javax.swing.JButton btnJogador2;
    private javax.swing.JButton btnJogador3;
    private javax.swing.JButton btnJogador4;
    private javax.swing.JButton btnJogador5;
    private javax.swing.JButton btnJogador6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JPanel pnlBotoesPrincipais;
    // End of variables declaration//GEN-END:variables
}
