/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.dialogs;

import enums.PosicaoJogador;
import gerentes.GerenteJogador;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author 13269098600
 */
public class PesquisaJogador extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PesquisaJogador.class.getName());
    /**
     * Creates new form PesquisaJogador
     */
    
    private GerenteJogador gerenteJogador;
    
    public PesquisaJogador(java.awt.Frame parent, boolean modal, GerenteJogador gerenteJogador) {
        super(parent, modal);
        
        this.gerenteJogador = gerenteJogador;
        
        initComponents();
        
        cbPosicao.setBackground(new Color(27,27,27));
        cbPosicao.setForeground(Color.WHITE);
        
        cbPosicao.setRenderer(new javax.swing.DefaultListCellRenderer() {

    @Override
    public java.awt.Component getListCellRendererComponent(
            javax.swing.JList<?> list,
            Object value,
            int index,
            boolean isSelected,
            boolean cellHasFocus) {

        javax.swing.JLabel item =
                (javax.swing.JLabel)
                super.getListCellRendererComponent(
                        list,
                        value,
                        index,
                        isSelected,
                        cellHasFocus);

        item.setForeground(Color.WHITE);

        if (isSelected) {
            item.setBackground(new Color(204,0,204));
        } else {
            item.setBackground(new Color(27,27,27));
        }

        return item;
    }
    
    
});

cbPosicao.setFocusable(false);
        
        getContentPane().setBackground(new Color(27,27,27));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PainelNomeAtleta = new javax.swing.JPanel();
        lblNomeAtleta = new javax.swing.JLabel();
        lblSetNomeAtleta = new javax.swing.JTextField();
        lblPosicaoAtleta = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        cbPosicao = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(27, 27, 27));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        PainelNomeAtleta.setBackground(new java.awt.Color(100, 100, 100));
        PainelNomeAtleta.setOpaque(false);
        PainelNomeAtleta.setRequestFocusEnabled(false);
        PainelNomeAtleta.setVerifyInputWhenFocusTarget(false);

        lblNomeAtleta.setBackground(new java.awt.Color(51, 51, 51));
        lblNomeAtleta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeAtleta.setText("Nome do Atleta");

        lblSetNomeAtleta.setBackground(new java.awt.Color(0, 0, 0));
        lblSetNomeAtleta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSetNomeAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lblSetNomeAtleta.addActionListener(this::lblSetNomeAtletaActionPerformed);

        javax.swing.GroupLayout PainelNomeAtletaLayout = new javax.swing.GroupLayout(PainelNomeAtleta);
        PainelNomeAtleta.setLayout(PainelNomeAtletaLayout);
        PainelNomeAtletaLayout.setHorizontalGroup(
            PainelNomeAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNomeAtleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSetNomeAtleta)
        );
        PainelNomeAtletaLayout.setVerticalGroup(
            PainelNomeAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNomeAtletaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeAtleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSetNomeAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lblPosicaoAtleta.setBackground(new java.awt.Color(51, 51, 51));
        lblPosicaoAtleta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPosicaoAtleta.setForeground(new java.awt.Color(255, 255, 255));
        lblPosicaoAtleta.setText("Posição do Atleta");

        btnBuscar.setBackground(new java.awt.Color(51, 51, 51));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(204, 0, 204));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        cbPosicao.setBackground(new java.awt.Color(0, 0, 0));
        cbPosicao.setForeground(new java.awt.Color(255, 255, 255));
        cbPosicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qualquer", "GOL", "ZAG", "LD", "LE", "VOL", "MC", "MEI", "PD", "PE", "ATA", " " }));
        cbPosicao.setLightWeightPopupEnabled(false);
        cbPosicao.setVerifyInputWhenFocusTarget(false);
        cbPosicao.addActionListener(this::cbPosicaoActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelNomeAtleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPosicaoAtleta, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbPosicao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelNomeAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPosicaoAtleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 475, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String nomeJogadorBusca = lblSetNomeAtleta.getText();
        
        String posicaoSelecionada = cbPosicao.getSelectedItem().toString();
        
        if(!nomeJogadorBusca.isBlank()){
            if(!posicaoSelecionada.equals("Qualquer")){
                PosicaoJogador posicaoJogadorBusca = PosicaoJogador.valueOf(posicaoSelecionada);
                for(int i = 0; i < gerenteJogador.getListaJogadores().size(); i++){
                    if(gerenteJogador.getListaJogadores().get(i).getNome().equals(nomeJogadorBusca) && gerenteJogador.getListaJogadores().get(i).getPosicao().equals(posicaoJogadorBusca)){
                        System.out.println(gerenteJogador.getListaJogadores().get(i).toString());
                    }
                }
            }
            else{
                for(int i = 0; i < gerenteJogador.getListaJogadores().size(); i++){
                    if(gerenteJogador.getListaJogadores().get(i).getNome().equals(nomeJogadorBusca)){
                        System.out.println(gerenteJogador.getListaJogadores().get(i).toString());
                    }
                }
            }
        }
        else{
            if(!posicaoSelecionada.equals("Qualquer")){
                PosicaoJogador posicaoJogadorBusca = PosicaoJogador.valueOf(posicaoSelecionada);
                for(int i = 0; i < gerenteJogador.getListaJogadores().size(); i++){
                    if(gerenteJogador.getListaJogadores().get(i).getPosicao().equals(posicaoJogadorBusca)){
                        System.out.println(gerenteJogador.getListaJogadores().get(i).toString());
                    }
                }
            }
            else{
                System.out.println("Selecione ao menos um filtro!");
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cbPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPosicaoActionPerformed
        
    }//GEN-LAST:event_cbPosicaoActionPerformed

    private void lblSetNomeAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSetNomeAtletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSetNomeAtletaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelNomeAtleta;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cbPosicao;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblNomeAtleta;
    private javax.swing.JLabel lblPosicaoAtleta;
    private javax.swing.JTextField lblSetNomeAtleta;
    // End of variables declaration//GEN-END:variables
}
